export const Copy = 'Copy'
export const OpenInNewTab = 'Open in New Tab'
export const OpenImageInNewTab = 'Open Image in New Tab'
export const SaveImageAs = 'Save Image as'
export const FileMatch = 'File Match'
export const Schema = 'Schema'
