import type { ExtensionDetailState } from '../ExtensionDetailState/ExtensionDetailState.ts'
import * as ExtensionDetailStates from '../ExtensionDetailStates/ExtensionDetailStates.ts'
import { getResponsiveLayout } from '../GetResponsiveLayout/GetResponsiveLayout.ts'

export const create = (uid: number, uri: string, x: number, y: number, width: number, height: number, platform: number, assetDir: string): void => {
  const state: ExtensionDetailState = {
    activationEntries: [],
    activationEvents: [],
    activationTime: 0,
    assetDir: assetDir || '',
    badge: '',
    baseUrl: '',
    builtinExtensionsBadgeEnabled: true,
    buttons: [],
    cacheName: '',
    categories: [],
    changelogScrollTop: 0,
    changelogVirtualDom: [],
    commands: [],
    commit: '',
    created: null,
    currentColorThemeId: '',
    description: '',
    detailsVirtualDom: [],
    disabled: false,
    displaySize: '',
    downloadCount: 'n/a',
    errorMessage: '',
    errorTitle: '',
    extension: {},
    extensionId: '',
    extensionUri: '',
    extensionVersion: '',
    features: [],
    featuresVirtualDom: [],
    focus: 0,
    focusedTabIndex: 0,
    folderSize: 0,
    hasColorTheme: false,
    hasReadme: false,
    iconSrc: '',
    importTime: 0,
    initial: true,
    installationEntries: [],
    jsonValidation: [],
    languages: [],
    lastUpdated: null,
    linkProtectionEnabled: false,
    locationHost: '',
    locationProtocol: '',
    marketplaceEntries: [],
    name: '',
    ...getResponsiveLayout(width),
    platform,
    programmingLanguages: [],
    rating: 'n/a',
    readmeScrollTop: 0,
    readmeUrl: '',
    resources: [],
    scrollSource: 0,
    scrollToTopButtonEnabled: false,
    selectedFeature: '',
    selectedTab: '',
    settings: [],
    settingsButtonEnabled: false,
    showAdditionalDetailsBreakpoint: 700,
    showSizeLink: false,
    sizeOnDisk: 0,
    sizeValue: 0,
    status: 0,
    tabs: [],
    themesMarkdownDom: [],
    uid,
    uri,
    wasActivatedByEvent: '',
    webViews: [],
    width,
  }
  ExtensionDetailStates.set(uid, state, state)
}
