import type { ExtensionDetailState } from '../ExtensionDetailState/ExtensionDetailState.ts'
import * as ExtensionDetailStates from '../ExtensionDetailStates/ExtensionDetailStates.ts'

export const create = (uid: number, uri: string, x: number, y: number, width: number, height: number, platform: number, assetDir: string): void => {
  const state: ExtensionDetailState = {
    wasActivatedByEvent: '',
    activationTime: 0,
    importTime: 0,
    disabled: false,
    status: 0,
    uid,
    activationEvents: [],
    assetDir: assetDir || '',
    badge: '',
    baseUrl: '',
    builtinExtensionsBadgeEnabled: true,
    buttons: [],
    categories: [],
    changelogScrollTop: 0,
    changelogVirtualDom: [],
    extensionUri: '',
    commands: [],
    hasReadme: false,
    description: '',
    detailsVirtualDom: [],
    displaySize: '',
    downloadCount: 'n/a',
    installationEntries: [],
    extension: {},
    extensionId: '',
    extensionVersion: '',
    features: [],
    featuresVirtualDom: [],
    focus: 0,
    folderSize: 0,
    hasColorTheme: false,
    iconSrc: '',
    jsonValidation: [],
    name: '',
    platform,
    programmingLanguages: [],
    rating: 'n/a',
    readmeScrollTop: 0,
    resources: [],
    scrollSource: 0,
    scrollToTopButtonEnabled: false,
    marketplaceEntries: [],
    selectedFeature: '',
    selectedTab: '',
    settings: [],
    settingsButtonEnabled: false,
    showAdditionalDetailsBreakpoint: 600,
    sizeOnDisk: 0,
    sizeValue: 0,
    tabs: [],
    themesMarkdownDom: [],
    uri,
    webViews: [],
    width,
    readmeUrl: '',
    paddingLeft: 0,
    paddingRight: 0,
  }
  ExtensionDetailStates.set(uid, state, state)
}
