export const commandIds = [
  'getMenuEntries',
  'handleClickDisable',
  'handleClickSetColorTheme',
  'handleClickSize',
  'handleClickUninstall',
  'handleFeaturesClick',
  'handleIconError',
  'handleTabsClick',
  'renderEventListeners',
  'resize',
  'saveState',
  'selectTab',
  'terminate',
]
