export const Changelog = 'Changelog'
export const Commands = 'Commands'
export const Details = 'Details'
export const Features = 'Features'
export const JsonValidation = 'JsonValidation'
export const ProgrammingLanguages = 'ProgrammingLanguages'
export const Settings = 'Settings'
export const Theme = 'Theme'
