export const ENOENT = 'ENOENT'
export const E_EXTENSION_NOT_FOUND = 'E_EXTENSION_NOT_FOUND'
export const E_FEATURE_NOT_FOUND = 'E_FEATURE_NOT_FOUND'
export const E_GITHUB_RELEASES = 'E_GITHUB_RELEASES'
