export const ExtensionDetailDescription = 'ExtensionDetailDescription'
export const ExtensionDetailHeader = 'ExtensionDetailHeader'
export const ExtensionDetailHeaderDetails = 'ExtensionDetailHeaderDetails'
export const ExtensionDetailIcon = 'ExtensionDetailIcon'
export const ExtensionDetailName = 'ExtensionDetailName'
export const Markdown = 'Markdown'
export const ExtensionDetail = 'ExtensionDetail'
export const Viewlet = 'Viewlet'
