import type { ExtensionDetailState } from '../ExtensionDetailState/ExtensionDetailState.ts'

export const createDefaultState = (overrides: Partial<ExtensionDetailState> = {}): ExtensionDetailState => {
  return {
    assetDir: '/test/asset/dir',
    baseUrl: '',
    builtinExtensionsBadgeEnabled: true,
    categories: [],
    changelogVirtualDom: [],
    description: '',
    detailsVirtualDom: [],
    displaySize: '',
    entries: [],
    extension: {},
    features: [],
    featuresVirtualDom: [],
    folderSize: 0,
    iconSrc: '',
    name: '',
    platform: 0,
    readmeScrollTop: 0,
    resources: [],
    scrollToTopButtonEnabled: false,
    secondEntries: [],
    selectedFeature: '',
    themesMarkdownDom: [],
    selectedTab: '',
    settingsButtonEnabled: false,
    showAdditionalDetailsBreakpoint: 600,
    sizeOnDisk: 0,
    uri: 'extension-detail://test-extension',
    width: 500,
    hasColorTheme: false,
    isBuiltin: false,
    sizeValue: 0,
    ...overrides,
  }
}
