import type { ExtensionDetailState } from '../ExtensionDetailState/ExtensionDetailState.ts'

export const createDefaultState = (overrides: Partial<ExtensionDetailState> = {}): ExtensionDetailState => {
  return {
    activationEvents: [],
    assetDir: '/test/asset/dir',
    baseUrl: '',
    builtinExtensionsBadgeEnabled: true,
    categories: [],
    changelogVirtualDom: [],
    commands: [],
    description: '',
    detailsVirtualDom: [],
    displaySize: '',
    entries: [],
    extension: {},
    extensionId: '',
    extensionVersion: '',
    features: [],
    featuresVirtualDom: [],
    folderSize: 0,
    hasColorTheme: false,
    iconSrc: '',
    isBuiltin: false,
    jsonValidation: [],
    name: '',
    platform: 0,
    programmingLanguages: [],
    readmeScrollTop: 0,
    resources: [],
    scrollToTopButtonEnabled: false,
    secondEntries: [],
    selectedFeature: '',
    selectedTab: '',
    settings: [],
    settingsButtonEnabled: false,
    showAdditionalDetailsBreakpoint: 600,
    sizeOnDisk: 0,
    sizeValue: 0,
    themesMarkdownDom: [],
    uri: 'extension-detail://test-extension',
    webViews: [],
    width: 500,
    ...overrides,
  }
}
