import type { ExtensionDetailState } from '../ExtensionDetailState/ExtensionDetailState.ts'

export const createDefaultState = (): ExtensionDetailState => {
  return {
    activationEvents: [],
    assetDir: '/test/asset/dir',
    badge: '',
    baseUrl: '',
    builtinExtensionsBadgeEnabled: true,
    buttons: [],
    categories: [],
    changelogScrollTop: 0,
    changelogVirtualDom: [],
    commands: [],
    description: '',
    detailsVirtualDom: [],
    displaySize: '',
    entries: [],
    extension: {},
    extensionId: '',
    extensionVersion: '',
    features: [],
    featuresVirtualDom: [],
    focus: 0,
    folderSize: 0,
    hasColorTheme: false,
    iconSrc: '',
    jsonValidation: [],
    name: '',
    platform: 0,
    programmingLanguages: [],
    readmeScrollTop: 0,
    resources: [],
    scrollSource: 0,
    scrollToTopButtonEnabled: false,
    secondEntries: [],
    selectedFeature: '',
    selectedTab: '',
    settings: [],
    settingsButtonEnabled: false,
    showAdditionalDetailsBreakpoint: 600,
    sizeOnDisk: 0,
    sizeValue: 0,
    tabs: [],
    themesMarkdownDom: [],
    uid: 0,
    uri: 'extension-detail://test-extension',
    webViews: [],
    width: 500,
    readmeUrl: '',
  }
}
